---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/telegraf --version
    register: telegraf_test_output
  - debug:
      msg: '{{ telegraf_test_output.stdout }}'
