---
- name: Testing andrewrothstein.telegraf
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'telegraf --version'
      ansible.builtin.command: /usr/local/bin/telegraf --version
      changed_when: false
      register: telegraf_test_output
    - name: Output from 'telegraf --version'
      ansible.builtin.debug:
        msg: '{{ telegraf_test_output.stdout }}'
