---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for telegraf install
  become: yes
  stat:
    path: '{{ telegraf_install_dir }}'
  changed_when: False
  register: telegraf_binary
- when: not telegraf_binary.stat.exists
  block:
    - name: download archive
      become: yes
      become_user: root
      get_url:
        url: '{{ telegraf_url }}'
        dest: /tmp/{{ telegraf_archive }}
        mode: 0644
        checksum: '{{ telegraf_checksum }}'
    - name: unarchive
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: /tmp/{{ telegraf_archive }}
        dest: '{{ telegraf_parent_install_dir }}'
        creates: '{{ telegraf_install_dir }}'
  always:
    - name: cleanup
      become: yes
      become_user: root
      file:
        path: /tmp/{{ telegraf_archive }}
        state: absent
- name: link telegraf directory
  become: yes
  become_user: root
  file:
    src: '{{ telegraf_install_dir }}'
    dest: '{{ telegraf_link_dir }}'
    state: link
- name: link telegraf binary
  become: yes
  become_user: root
  file:
    src: '{{ telegraf_link_dir }}/usr/bin/telegraf'
    dest: '{{ telegraf_parent_install_dir }}/bin/telegraf'
    state: link
